export type SupportedLanguage =
  | 'en'
  | 'hi'
  | 'kn'
  | 'as'
  | 'bn'
  | 'mni'
  | 'brx'
  | 'lus'
  | 'kha'
  | 'grt'
  | 'trp'
  | 'ten'
  | 'ao'
  | 'lot';

export type VoicePackAvailability =
  | 'Installed'
  | 'Unavailable Offline'
  | 'Coming Soon'
  | 'Ready';

export interface LanguageConfigEntry {
  code: SupportedLanguage;
  locale: string;
  englishName: string;
  nativeName: string;
  flag: string;
  region: string;
  script: string;
  uiStatus: 'Installed';
  ttsStatus: VoicePackAvailability;
  sttStatus: VoicePackAvailability;
  modelSize: string;
  modelVersion: string;
  checksumSha256?: string;
  asrModel?: string;
  ttsModel?: string;
  asrModelFamily: string;
  ttsModelFamily: string;
  officialAsrSource: string;
  officialTtsSource: string;
  testPhrase: string;
}

export const LANGUAGE_CONFIG: Record<SupportedLanguage, LanguageConfigEntry> = {
  en: {
    code: 'en',
    locale: 'en-IN',
    englishName: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    region: 'Pan-India / International',
    script: 'Latin',
    uiStatus: 'Installed',
    ttsStatus: 'Installed',
    sttStatus: 'Installed',
    modelSize: '24 MB',
    modelVersion: '1.0.0',
    checksumSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    asrModel: 'en',
    ttsModel: 'en',
    asrModelFamily: 'Standard In-Browser / Local Device ASR',
    ttsModelFamily: 'Standard In-Browser / Local Device TTS',
    officialAsrSource: 'local',
    officialTtsSource: 'local',
    testPhrase: 'Hello, I am here to assist you.',
  },
  hi: {
    code: 'hi',
    locale: 'hi-IN',
    englishName: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    region: 'National / NER Urban Bridge',
    script: 'Devanagari',
    uiStatus: 'Installed',
    ttsStatus: 'Installed',
    sttStatus: 'Installed',
    modelSize: '142 MB',
    modelVersion: '1.0.0',
    checksumSha256: '9a7d3c2b1e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    asrModel: 'hi',
    ttsModel: 'hi',
    asrModelFamily: 'AI4Bharat IndicConformer ASR',
    ttsModelFamily: 'AI4Bharat Indic-TTS',
    officialAsrSource: 'ai4bharat/indicconformer_stt_hi_hybrid_ctc_rnnt_large',
    officialTtsSource: 'https://github.com/AI4Bharat/Indic-TTS/releases/download/v1-checkpoints-release/hi.zip',
    testPhrase: 'नमस्ते, मैं आपकी सहायता के लिए यहाँ हूँ।',
  },
  kn: {
    code: 'kn',
    locale: 'kn-IN',
    englishName: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    region: 'South / Cross-Regional Benchmark',
    script: 'Kannada',
    uiStatus: 'Installed',
    ttsStatus: 'Installed',
    sttStatus: 'Installed',
    modelSize: '138 MB',
    modelVersion: '1.0.0',
    checksumSha256: '8b6e4d2c1a3f5e7a9c1b3d5f7e9a1c3b5d7f9e1a3c5b7d9f1e3a5c7b9d1f3e5a',
    asrModel: 'kn',
    ttsModel: 'kn',
    asrModelFamily: 'AI4Bharat IndicConformer ASR',
    ttsModelFamily: 'AI4Bharat Indic-TTS',
    officialAsrSource: 'ai4bharat/indicconformer_stt_kn_hybrid_ctc_rnnt_large',
    officialTtsSource: 'https://github.com/AI4Bharat/Indic-TTS/releases/download/v1-checkpoints-release/kn.zip',
    testPhrase: 'ನಮಸ್ಕಾರ, ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ಇಲ್ಲಿದ್ದೇನೆ.',
  },
  as: {
    code: 'as',
    locale: 'as-IN',
    englishName: 'Assamese',
    nativeName: 'অসমীয়া',
    flag: '🇮🇳',
    region: 'Assam / Brahmaputra Valley',
    script: 'Bengali-Assamese',
    uiStatus: 'Installed',
    ttsStatus: 'Installed',
    sttStatus: 'Installed',
    modelSize: '124 MB',
    modelVersion: '1.0.0',
    checksumSha256: '7c5e3d1a9b2f4e6a8c0b2d4f6e8a0c2b4d6f8e0a2c4b6d8f0e2a4c6b8d0f2e4a',
    asrModelFamily: 'AI4Bharat IndicConformer ASR',
    ttsModelFamily: 'AI4Bharat Indic-TTS',
    officialAsrSource: 'ai4bharat/indicconformer_stt_as_hybrid_ctc_rnnt_large',
    officialTtsSource: 'https://github.com/AI4Bharat/Indic-TTS/releases/download/v1-checkpoints-release/as.zip',
    testPhrase: 'নমস্কাৰ, মই আপোনাক সহায় কৰিবলৈ ইয়াত আছোঁ।',
  },
  bn: {
    code: 'bn',
    locale: 'bn-IN',
    englishName: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇮🇳',
    region: 'Barak Valley / Tripura',
    script: 'Bengali',
    uiStatus: 'Installed',
    ttsStatus: 'Installed',
    sttStatus: 'Installed',
    modelSize: '135 MB',
    modelVersion: '1.0.0',
    checksumSha256: '6b4d2c0a8b1f3e5a7c9b1d3f5e7a9c1b3d5f7e9a1c3b5d7f9e1a3c5b7d9f1e3a',
    asrModelFamily: 'AI4Bharat IndicConformer ASR',
    ttsModelFamily: 'AI4Bharat Indic-TTS',
    officialAsrSource: 'ai4bharat/indicconformer_stt_bn_hybrid_ctc_rnnt_large',
    officialTtsSource: 'https://github.com/AI4Bharat/Indic-TTS/releases/download/v1-checkpoints-release/bn.zip',
    testPhrase: 'নমস্কার, আমি আপনাকে সাহায্য করার জন্য এখানে আছি।',
  },
  mni: {
    code: 'mni',
    locale: 'mni-IN',
    englishName: 'Meitei / Manipuri',
    nativeName: 'মেইতেই / Manipuri',
    flag: '🇮🇳',
    region: 'Manipur (Imphal Valley)',
    script: 'Meitei Mayek / Bengali',
    uiStatus: 'Installed',
    ttsStatus: 'Unavailable Offline',
    sttStatus: 'Unavailable Offline',
    modelSize: 'N/A (Pipeline Staged)',
    modelVersion: '0.8.0-dev',
    asrModelFamily: 'AI4Bharat IndicSpeech (In Development)',
    ttsModelFamily: 'AI4Bharat Indic-TTS Research Scaffold',
    officialAsrSource: 'ai4bharat/indicspeech_mni_experimental',
    officialTtsSource: 'https://github.com/AI4Bharat/Indic-TTS/tree/main/models/mni',
    testPhrase: 'খুরুমজরি, ঐহাক্না নখোয়দা মতেং পাংনবা মফমসিদা লৈরি।',
  },
  brx: {
    code: 'brx',
    locale: 'brx-IN',
    englishName: 'Bodo',
    nativeName: 'बड़ो',
    flag: '🇮🇳',
    region: 'Bodoland Territorial Region (BTR)',
    script: 'Devanagari',
    uiStatus: 'Installed',
    ttsStatus: 'Unavailable Offline',
    sttStatus: 'Unavailable Offline',
    modelSize: 'N/A (Pipeline Staged)',
    modelVersion: '0.8.0-dev',
    asrModelFamily: 'AI4Bharat IndicSpeech (In Development)',
    ttsModelFamily: 'AI4Bharat Indic-TTS Research Scaffold',
    officialAsrSource: 'ai4bharat/indicspeech_brx_experimental',
    officialTtsSource: 'https://github.com/AI4Bharat/Indic-TTS/tree/main/models/brx',
    testPhrase: 'खुलुमबाय, आं नोंखौ हेफाजाब होनो थाखाय बेयाव दं।',
  },
  lus: {
    code: 'lus',
    locale: 'lus-IN',
    englishName: 'Mizo',
    nativeName: 'Mizo ṭawng',
    flag: '🇮🇳',
    region: 'Mizoram',
    script: 'Latin',
    uiStatus: 'Installed',
    ttsStatus: 'Coming Soon',
    sttStatus: 'Coming Soon',
    modelSize: 'N/A (Roadmap Q4)',
    modelVersion: '0.5.0-staged',
    asrModelFamily: 'NER Community Acoustic Engine',
    ttsModelFamily: 'NER Community Synthesis Engine',
    officialAsrSource: 'ner-mind/acoustic_models/lus',
    officialTtsSource: 'ner-mind/synthesis_models/lus',
    testPhrase: 'Chibai, pui tur chein ka awm e.',
  },
  kha: {
    code: 'kha',
    locale: 'kha-IN',
    englishName: 'Khasi',
    nativeName: 'Ka Ktien Khasi',
    flag: '🇮🇳',
    region: 'Meghalaya (Khasi Hills)',
    script: 'Latin',
    uiStatus: 'Installed',
    ttsStatus: 'Unavailable Offline',
    sttStatus: 'Unavailable Offline',
    modelSize: 'N/A (Pipeline Staged)',
    modelVersion: '0.8.0-dev',
    asrModelFamily: 'AI4Bharat / Martin Luther Christian Univ Collaborative',
    ttsModelFamily: 'Khasi Regional Speech Synthesis',
    officialAsrSource: 'ner-mind/speech/kha',
    officialTtsSource: 'ner-mind/tts/kha',
    testPhrase: 'Khublei, nga don hangne ban iarap ia phi.',
  },
  grt: {
    code: 'grt',
    locale: 'grt-IN',
    englishName: 'Garo',
    nativeName: 'A·chik',
    flag: '🇮🇳',
    region: 'Meghalaya (Garo Hills)',
    script: 'Latin',
    uiStatus: 'Installed',
    ttsStatus: 'Coming Soon',
    sttStatus: 'Coming Soon',
    modelSize: 'N/A (Roadmap Q4)',
    modelVersion: '0.5.0-staged',
    asrModelFamily: 'NER Community Acoustic Engine',
    ttsModelFamily: 'NER Community Synthesis Engine',
    officialAsrSource: 'ner-mind/acoustic_models/grt',
    officialTtsSource: 'ner-mind/synthesis_models/grt',
    testPhrase: 'Salam, anga nang·na dakchakaniko on·na iano donga.',
  },
  trp: {
    code: 'trp',
    locale: 'trp-IN',
    englishName: 'Kokborok',
    nativeName: 'ককবরক',
    flag: '🇮🇳',
    region: 'Tripura (Tripuri community)',
    script: 'Bengali / Latin',
    uiStatus: 'Installed',
    ttsStatus: 'Coming Soon',
    sttStatus: 'Coming Soon',
    modelSize: 'N/A (Roadmap Q4)',
    modelVersion: '0.5.0-staged',
    asrModelFamily: 'Tripura Tribal Language Lab Engine',
    ttsModelFamily: 'Kokborok Regional Synthesis Model',
    officialAsrSource: 'ner-mind/acoustic_models/trp',
    officialTtsSource: 'ner-mind/synthesis_models/trp',
    testPhrase: 'Khulumkha, ang nwngno chubachu rwnani omohai tongo.',
  },
  ten: {
    code: 'ten',
    locale: 'ten-IN',
    englishName: 'Tenyidie (Naga)',
    nativeName: 'Tenyidie',
    flag: '🇮🇳',
    region: 'Nagaland (Kohima / Southern Angami)',
    script: 'Latin',
    uiStatus: 'Installed',
    ttsStatus: 'Coming Soon',
    sttStatus: 'Coming Soon',
    modelSize: 'N/A (Roadmap Q4)',
    modelVersion: '0.5.0-staged',
    asrModelFamily: 'Nagaland State Language Project',
    ttsModelFamily: 'Ura Academy Language Synthesis',
    officialAsrSource: 'ner-mind/acoustic_models/ten',
    officialTtsSource: 'ner-mind/synthesis_models/ten',
    testPhrase: 'Vitho, a n kekrü kemenu la ha ba.',
  },
  ao: {
    code: 'ao',
    locale: 'ao-IN',
    englishName: 'Ao (Naga)',
    nativeName: 'Ao Chungli',
    flag: '🇮🇳',
    region: 'Nagaland (Mokokchung)',
    script: 'Latin',
    uiStatus: 'Installed',
    ttsStatus: 'Coming Soon',
    sttStatus: 'Coming Soon',
    modelSize: 'N/A (Roadmap Q4)',
    modelVersion: '0.5.0-staged',
    asrModelFamily: 'Nagaland State Language Project',
    ttsModelFamily: 'Ao Regional Language Synthesis',
    officialAsrSource: 'ner-mind/acoustic_models/ao',
    officialTtsSource: 'ner-mind/synthesis_models/ao',
    testPhrase: 'Koma, ni na yariteptsü atema iba nung lir.',
  },
  lot: {
    code: 'lot',
    locale: 'lot-IN',
    englishName: 'Lotha (Naga)',
    nativeName: 'Kyong',
    flag: '🇮🇳',
    region: 'Nagaland (Wokha)',
    script: 'Latin',
    uiStatus: 'Installed',
    ttsStatus: 'Coming Soon',
    sttStatus: 'Coming Soon',
    modelSize: 'N/A (Roadmap Q4)',
    modelVersion: '0.5.0-staged',
    asrModelFamily: 'Nagaland State Language Project',
    ttsModelFamily: 'Lotha Regional Language Synthesis',
    officialAsrSource: 'ner-mind/acoustic_models/lot',
    officialTtsSource: 'ner-mind/synthesis_models/lot',
    testPhrase: 'Aroha, a na a tssori thung eba vamo.',
  },
};
