import { TaskContext } from '../../types/observation.js';

export interface RegionalRecognitionObject {
  id: string;
  name: string;
  localName: string;
  icon: string;
  description: string;
  category: 'apparel' | 'utensil' | 'tool' | 'instrument' | 'craft' | 'vessel' | 'container';
  material: 'bamboo' | 'silk' | 'bell_metal' | 'clay' | 'wood' | 'brass';
  context: TaskContext;
}

export const REGIONAL_RECOGNITION_OBJECTS: RegionalRecognitionObject[] = [
  // Traditional Headwear & Apparel
  {
    id: 'bamboo_jaapi',
    name: 'Bamboo Jaapi',
    localName: 'জাপী',
    icon: '👒',
    description: 'Traditional conical hat woven from tight bamboo strips and dried palm leaves, decorated with red felt',
    category: 'apparel',
    material: 'bamboo',
    context: 'craft',
  },
  {
    id: 'gamusa_cloth',
    name: 'Assamese Gamusa',
    localName: 'গামোচা',
    icon: '🧣',
    description: 'Handwoven white rectangular cotton/silk towel adorned with traditional red woven borders given as mark of honour',
    category: 'apparel',
    material: 'silk',
    context: 'craft',
  },
  {
    id: 'muga_mekhela_sador',
    name: 'Muga Mekhela Sador',
    localName: 'মুগা মেখেলা চাদৰ',
    icon: '👘',
    description: 'Two-piece indigenous golden silk traditional dress worn by women during ceremonies',
    category: 'apparel',
    material: 'silk',
    context: 'craft',
  },
  {
    id: 'eri_shawl',
    name: 'Eri Peace Silk Shawl',
    localName: 'এৰী চাদৰ',
    icon: '🧶',
    description: 'Warm, textured cream-coloured handloom shawl spun from non-violent domesticated silkworms',
    category: 'apparel',
    material: 'silk',
    context: 'craft',
  },
  {
    id: 'khasi_jainsem',
    name: 'Khasi Jainsem Dress',
    localName: 'Jainsem',
    icon: '👗',
    description: 'Graceful two-piece mulberry silk attire draped elegantly across both shoulders by Khasi women',
    category: 'apparel',
    material: 'silk',
    context: 'craft',
  },

  // Bell Metal & Brass Vessels
  {
    id: 'bell_metal_kahi',
    name: 'Sarthebari Bell Metal Kahi (Plate)',
    localName: 'কাঁহী',
    icon: '🍽️',
    description: 'Heavy traditional handmade bronze/bell-metal dining platter with raised curved rim',
    category: 'utensil',
    material: 'bell_metal',
    context: 'household',
  },
  {
    id: 'bell_metal_bati',
    name: 'Sarthebari Bell Metal Bati (Bowl)',
    localName: 'বাটি',
    icon: '🥣',
    description: 'Traditional small bell-metal bowl for serving lentil dal and herbal vegetable soups',
    category: 'utensil',
    material: 'bell_metal',
    context: 'household',
  },
  {
    id: 'brass_lota',
    name: 'Engraved Brass Lota',
    localName: 'লোটা',
    icon: '🏺',
    description: 'Round brass pitcher with narrow neck used for pouring clean drinking water and morning oblations',
    category: 'vessel',
    material: 'brass',
    context: 'household',
  },
  {
    id: 'brass_sarai',
    name: 'Xorai (Offering Tray with Stand)',
    localName: 'শৰাই',
    icon: '🏆',
    description: 'Ornate raised brass tray on pedestal used to present betel leaves, gifts, and prayer offerings',
    category: 'vessel',
    material: 'brass',
    context: 'community',
  },
  {
    id: 'bell_metal_kalah',
    name: 'Kalah (Bell Metal Water Urn)',
    localName: 'কলহ',
    icon: '🫙',
    description: 'Large bulbous water urn hammered from bell metal for keeping well water naturally cool',
    category: 'vessel',
    material: 'bell_metal',
    context: 'household',
  },

  // Bamboo & Cane Utensils & Containers
  {
    id: 'bamboo_khorahi',
    name: 'Khorahi (Open Weave Bamboo Basket)',
    localName: 'খোৰাহী',
    icon: '🧺',
    description: 'Shallow basket woven from green bamboo splits used for washing fresh vegetables and greens',
    category: 'container',
    material: 'bamboo',
    context: 'kitchen',
  },
  {
    id: 'bamboo_chalani',
    name: 'Chalani (Bamboo Flour Sieve)',
    localName: 'চালনী',
    icon: '🕸️',
    description: 'Circular woven bamboo sieve with fine mesh holes for sifting rice flour and husk',
    category: 'tool',
    material: 'bamboo',
    context: 'kitchen',
  },
  {
    id: 'bamboo_pula',
    name: 'Dula / Pula (Grain Storage Basket)',
    localName: 'ডুলা',
    icon: '📦',
    description: 'Large cylindrical tightly woven bamboo storage silo lined with cowdung clay to preserve paddy',
    category: 'container',
    material: 'bamboo',
    context: 'household',
  },
  {
    id: 'bisoni_cane_fan',
    name: 'Bisoni (Handwoven Cane Hand Fan)',
    localName: 'বিচনী',
    icon: '🪭',
    description: 'Lightweight heart-shaped hand fan woven from fine cane with wooden bamboo handle',
    category: 'tool',
    material: 'bamboo',
    context: 'household',
  },
  {
    id: 'polo_fishing_basket',
    name: 'Polo (Conical Bamboo Fish Trap)',
    localName: 'পলো',
    icon: '🪤',
    description: 'Open-ended conical plunge basket woven from bamboo slats used for catching river fish in shallow water',
    category: 'tool',
    material: 'bamboo',
    context: 'routine',
  },
  {
    id: 'jakoi_triangular_trap',
    name: 'Jakoi (Triangular Bamboo Fish Scoop)',
    localName: 'জাকৈ',
    icon: '📐',
    description: 'Triangular scoop cage woven from bamboo splints used by women in wetlands to scoop small fish',
    category: 'tool',
    material: 'bamboo',
    context: 'routine',
  },

  // Agricultural & Wooden Household Tools
  {
    id: 'wooden_dheki',
    name: 'Dheki (Wooden Rice Pounder Lever)',
    localName: 'ঢেঁকী',
    icon: '🪵',
    description: 'Heavy wooden foot-operated lever mechanism with pestle used to de-husk paddy into aromatic rice',
    category: 'tool',
    material: 'wood',
    context: 'household',
  },
  {
    id: 'kula_winnowing_fan',
    name: 'Kula (U-Shaped Winnowing Fan)',
    localName: 'কুলা',
    icon: '🥏',
    description: 'Scoop-shaped bamboo tray tossed by hand to let wind separate chaff from harvested rice grains',
    category: 'tool',
    material: 'bamboo',
    context: 'household',
  },
  {
    id: 'wooden_urral',
    name: 'Urral (Carved Wooden Mortar & Pestle)',
    localName: 'উৰাল',
    icon: '🪵',
    description: 'Solid hardwood hollowed tree trunk mortar used with wooden pestle to pound roasted rice and spices',
    category: 'tool',
    material: 'wood',
    context: 'kitchen',
  },

  // Traditional Musical Instruments
  {
    id: 'bihu_dhol',
    name: 'Bihu Dhol (Double-Headed Drum)',
    localName: 'ঢোল',
    icon: '🥁',
    description: 'Two-sided wooden barrel drum played with bamboo stick on one side and bare hand on the other',
    category: 'instrument',
    material: 'wood',
    context: 'community',
  },
  {
    id: 'pepa_buffalo_horn',
    name: 'Pepa (Buffalo Horn Trumpet)',
    localName: 'পেঁপা',
    icon: '🎺',
    description: 'Piercing reed horn crafted from curved Asiatic buffalo horn with small bamboo mouthpiece',
    category: 'instrument',
    material: 'bamboo',
    context: 'community',
  },
  {
    id: 'gogona_jaw_harp',
    name: 'Gogona (Bamboo Jaw Harp)',
    localName: 'গগনা',
    icon: '🎵',
    description: 'Vibrating bamboo lamellophone played held between teeth by young women during Spring Bihu dances',
    category: 'instrument',
    material: 'bamboo',
    context: 'community',
  },
  {
    id: 'tokari_folk_lute',
    name: 'Tokari (Folk Plucked Lute)',
    localName: 'টোকোৰী',
    icon: '🪕',
    description: 'Folk plucked string instrument carved from Bel fruit or wood with parchment soundboard',
    category: 'instrument',
    material: 'wood',
    context: 'community',
  },
  {
    id: 'taal_cymbals',
    name: 'Bhor Taal (Large Bronze Cymbals)',
    localName: 'ভোৰতাল',
    icon: '🪙',
    description: 'Heavy clashing bronze cymbals used in monastery chanting and devotional Naam Kirtan prayer songs',
    category: 'instrument',
    material: 'bell_metal',
    context: 'community',
  },
];
